### ISSUE TITLE
How would you describe your design process?

### ISSUE THREAD

**Issue by mijustin** [thexavismith/ama#1]
Specifically I'm interested in _how you go from a concept to finished HTML, CSS, and JavaScript._

**Comment by thexavismith** [comment]
That's an excellent question! I'll preface all of this by saying that it's all relative to what's being worked on. Some projects require more that others. I'll describe the process that I followed to redesign Drupalize.me and mix in some parts from other places. [You can find Drupalize.me in my portfolio](https://ttimsmith.com/portfolio/drupalize-me/).

### Step 1: Gather User Data

We knew we wanted to redesign Drupalize.me; the look felt very web 2.0 and dated. But aesthetics are only one part of the problem, so we decided to survey our users. We used some well placed questions to gather information from them. I don't remember exactly the questions in the survey but they were something like this:
- What do you like about Drupalize.me?
- What is your biggest pain point?
- Do you feel the feedback process can be improved? How?
- What frustrates you about Drupalize.me?
- When viewing your dashboard, what's most important?

Other than that, we also asked demographical questions like age, gender, industry, role, reason for subscribing, etc.

This data really helped shape our product roadmap moving forward. It helped me have clarity and focus on what was most important.

### Step 2: Low-Fi Mockups

Some people call this wireframing. Whatever it is you call it, it's a vital part of the process. Here, we keep things as low fidelity as possible. Meaning we use little to no color, and use default typography (San Francisco, Helvetica, etc). The objective here is to not distract with too many details. You color something brown, and everyone will focus on how brown is the color of 💩 so we can't use it. Really, we're trying to get feedback on whether the information is architected well on the page, if the flow of the onboarding feels right, or if interactions feel confusing.

This is where I like to spend most of my time and iterate here as much as possible. The most number of versions of had of one wireframe was probably about 10. Usually by those last wireframes, you're not changing huge things… hopefully.

### Step 3: Hi-Fi Mockups/Browser Implimentation

So this is kind of two steps in one because the lines here blur for me. I've always liked to implement designs as soon as possible. For me, that means making a lot of these aesthetic decisions in the browser. It's just so much easier to make something in HTML/CSS, then working in Photoshop or Sketch. It also makes making changes so much easier! I had a client where I changed a shade of a color over 10 times! It was kind of ridiculous in the browser, would've been much more if I'd used a design program.

Again, this stage will have some revisions, but the goal is to keep them much lower than the wireframing stage. _There should be no major changes of components and their placement in this stage_. Those things should be worked out in wireframing. Here, we're looking at color, typography, iconography, aesthetic details like shadows, hover states, focus states, animations, etc.

This stage is much easier if you have a design system, and if you're working on a product, you should be using a design system. This will minimize the friction in many of these steps, since there is a library of components that you try to use first before making something from scratch.

### Step 4: Collaboration with Engineering Teams

Again depending on the project, either I implement my frontend markup and then it's hooked up on the backend, or the backend stuff is done first, and I'll hook it up with the frontend. At [ACL](https://twitter.com/aclservices), this is how we work and often pull requests have commits from myself and a backend engineer where we work closely to button it all up. Once the backend stuff is complete, I'll always come back and make sure that the design is still in tact and that there aren't any visual bugs.

### Step 5: Merge/Deploy

You push the green button and it all starts over again! There's always something to improve, so in product work you start working on the next version or on another feature. On a marketing site, this is where the work ends(for now) and you pop the champagne bottle
