### ISSUE TITLE
How do you recover from coffee addiction?

### ISSUE THREAD

**Issue by elderfo** [thexavismith/ama#4]
I think I was addicted in my 20s, I drank coffee all day and never slept.

**Comment by thexavismith** [comment]
haha! Thanks for the question @elderfo. I think each person has their own path from coffee addiction, but for me it's been allowing myself to have one cup of joe a day, and then replacing the rest of the cups with water. Unfortunately, for me it was because the amount of caffeine I was consuming was giving me severe anxiety. If I had more than one cup, I'd get an anxiety attack. Still, I knew I shouldn't be drinking 3-4 cups a day, and without me noticing it was affecting my sleep too.

Since reducing the amount of coffee I drink, I've felt much less anxiety, sleep better, and feel generally healthier by drinking more water. But I want to make it clear, **I still drink coffee**. I love it. I just drink *less* of it.

**Comment by elderfo** [comment]
Drink in moderation, eh?

@smithtimmytim I am glad to hear that reducing your coffee intake has helped with anxiety. Anxiety is not fun. I limit my intake as well, allowing myself 1 cup, albeit a large cup. When it's done, I do the same as you, switch to water.

What's your favorite coffee?

**Comment by thexavismith** [comment]
oh awesome! Umm I have a few places I buy from:

- [Verve Coffee](https://www.vervecoffee.com/)
- [Madcap Coffee](https://madcapcoffee.com/)
- [Cuvee Coffee](http://cuveecoffee.com/)
- [Cafe Grumpy](http://cafegrumpy.com/)
- [Craft Coffee](https://www.craftcoffee.com/)

**Comment by elderfo** [comment]
I am not really fancy with my coffee, though I have graduated to grinding my own every morning. I still get my beans from the grocery store. So those links will be a great place to look.

I usually like dark strong flavored coffee and I drink it black. I once had a friend tell encourage me to keep drinking cheap pre-ground coffee and stay away from the good stuff because I'll never be able to turn back. Kind of like craft beer. haha. I think i am going to ignore that piece of advice.
